version: "1.0"

#############################
# Owner: Bahaeddine FERIANI #
#############################

services:
  pyspark:
    container_name: pyspark
    image: pyspark
    restart: on-failure
    ports:
      - "8888:8888"
    volumes:
      - ./data:/data
    networks:
      - kepler
networks:
  kepler:
    name: kepler
    driver: bridge
